### ISSUE TITLE
Error detecting params.json using docker in debian (10) HPC

### ISSUE THREAD

**Issue by ap1438** [google/deepconsensus#55]
docker run google/deepconsensus:1.1.0 deepconsensus run --subreads_to_ccs=m54274Ue_220814_163631.aligned.subreads.bam --ccs_bam=m54274Ue_220814_163631.hifi_S3_reads.bam --checkpoint=model/checkpoint --output=m54274Ue_220814_163631_deepcon.output.fastq
Traceback (most recent call last):
File "/opt/conda/envs/bio/bin/deepconsensus", line 8, in
sys.exit(run())
File "/opt/conda/envs/bio/lib/python3.9/site-packages/deepconsensus/cli.py", line 111, in run
app.run(main, flags_parser=parse_flags)
File "/opt/conda/envs/bio/lib/python3.9/site-packages/absl/app.py", line 312, in run
_run_main(main, args)
File "/opt/conda/envs/bio/lib/python3.9/site-packages/absl/app.py", line 258, in _run_main
sys.exit(main(argv))
File "/opt/conda/envs/bio/lib/python3.9/site-packages/deepconsensus/cli.py", line 102, in main
app.run(quick_inference.main, argv=passed)
File "/opt/conda/envs/bio/lib/python3.9/site-packages/absl/app.py", line 312, in run
_run_main(main, args)
File "/opt/conda/envs/bio/lib/python3.9/site-packages/absl/app.py", line 258, in _run_main
sys.exit(main(argv))
File "/opt/conda/envs/bio/lib/python3.9/site-packages/deepconsensus/inference/quick_inference.py", line 842, in main
outcome_counter = run()
File "/opt/conda/envs/bio/lib/python3.9/site-packages/deepconsensus/inference/quick_inference.py", line 703, in run
params = model_utils.read_params_from_json(checkpoint_path=FLAGS.checkpoint)
File "/opt/conda/envs/bio/lib/python3.9/site-packages/deepconsensus/models/model_utils.py", line 405, in read_params_from_json
json.load(tf.io.gfile.GFile(json_path, 'r')))
File "/opt/conda/envs/bio/lib/python3.9/json/init.py", line 293, in load
return loads(fp.read(),
File "/opt/conda/envs/bio/lib/python3.9/site-packages/tensorflow/python/lib/io/file_io.py", line 116, in read
self._preread_check()
File "/opt/conda/envs/bio/lib/python3.9/site-packages/tensorflow/python/lib/io/file_io.py", line 77, in _preread_check
self._read_buf = _pywrap_file_io.BufferedInputStream(
tensorflow.python.framework.errors_impl.NotFoundError: model/params.json; No such file or directory

I am getting this error even though i have all the files from model
checkpoint.data-00000-of-00001
checkpoint.index
params.json
in the model dir.

**Comment by pichuan** [comment]
Hi @ap1438 ,
given that you're using Docker, you'll need to make sure the paths you passed in are visible through Docker.
The flag you'll need to add is `-v`. For example, in this section https://github.com/google/deepconsensus/blob/r1.1/docs/quick_start.md#running-the-docker-image , you can see that this flag was added `  -v "${QS_DIR}":/data`.

https://docs.docker.com/storage/volumes/ might also be helpful to read.

**Comment by ap1438** [comment]
It worked. Thankyou
